### ISSUE TITLE
Site title markup and headings hierarchy

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/mythic#17]
I personally use only one `h1` per page, it keeps headings hierarchy simple. And is current good practise for [HTML5 and accessibility](https://make.wordpress.org/accessibility/handbook/best-practices/markup/heading-structure-in-theme-development/).

Once again I [Underscores method is what I recommend](https://github.com/Automattic/_s/blob/master/header.php#L31).  This could also be template function to avoid `if else` in template files, see also issue #16.

**Comment by justintadlock** [comment]
I'll probably go back to the old `hybrid_site_title()` template tag we had before.

**Comment by justintadlock** [comment]
Perhaps we should do a review of the overall headings hierarchy of the entire theme and properly lay that out.

**Comment by samikeijonen** [comment]
> Perhaps we should do a review of the overall headings hierarchy of the entire theme and properly lay that out.

Definitely.

**Comment by justintadlock** [comment]
I want to get this done by the 1.0.0 release.  

Also, I want to quickly note that the comment pagination title/header should probably be an `h3` since it's below the `h2` header for the comments list.
