### ISSUE TITLE
Bundle command

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#32]
Bundling the theme for distribution is probably the last script we need.  It should be triggered from the command line like so:

```bash
npm run bundle
```

It should create a new folder in the theme named `mythic` (theme name) or simply `bundle`.  The idea is that theme authors would want the theme prepared for distribution with only the files that need to be uploaded to the site.

The following should be included:

```
- changelog.md      (not in the repo yet)
- functions.php
- index.php
- license.md
- readme.md
- screenshot.png
- style.css

- /app
- /dist
- /resources
	- /lang
	- /scripts      (WordPress.org-only)
	- /styles       (WordPress.org-only)
	- /views
- /vendor
```

WordPress.org requires the original script/style files when minifying them.  So, we'll want to have something commented out that theme authors can uncomment for those particular directories.

## Wepack config 

We could probably do a `webpack.config.bundle.js` file for this to keep it separate.  

Or, if someone knows how to integrate this into the `webpack.mix.js` and pass in a custom variable from the `scripts` line in `package.json`, that'd work.  Need something like:

```js
if ( bundle ) {
	mix.copy()...
}
```

This should be pretty basic.  We just need to let theme authors edit what files they might want to include and copy them all over with the `bundle` command.

**Comment by brettsmason** [comment]
We could potentially use a package like this:
https://www.npmjs.com/package/zip-webpack-plugin

I'll look into if we can pass a custom arguement or something to trigger it.

**Comment by justintadlock** [comment]
Closing this as fixed.
