### ISSUE TITLE
Alternatives to render() and fetch() terminology

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#35]
At the moment, we're using `render()` to mean "output" html and `fetch()` to mean "return" html.  Opening this up for discussion for alternatives.

**Comment by justintadlock** [comment]
Just copying/pasting from Twitter:

> I applaud the move away from `get_template_part()`, but maybe your terminology is misleading.
> - what you call `fetch()` is usually a `render()`, `fetch` implies a remote request
> - what you call `render()` is usually a `print()`, `render` is about the transformation, not sending

I could be down with a `render()` for returning HTML and a `print()` for outputting the HTML.

**Comment by justintadlock** [comment]
So, I've spent the last half hour or so (I know, not much time) looking over various libraries and just general online discussions.

---

My general feeling right now is that `render()` is probably the most confusing part of this.  The terminology seems to mean two different things, depending on what's being used.

`print()`, on the other hand is plain as day.  There's no confusion about what it means to print something.  I'm leaning toward changing `render()` to `print()` across the board.

---

As far as `fetch()` goes, I'm leaning toward keeping this term or an alternative that's not `render()`.  I think changing it to `render()` might introduce some confusion.  

Possibilities:

- `fetch()`
- `yield()`
- `toHtml()`

I don't like `get()` here because that's more arbitrary.  I'd like to use a specific term that applies to HTML returns as opposed to any sort of data.

**Comment by FrankM1** [comment]
Hi Justin, 

Good work on this project. Have you considered using the WordPress naming technique of adding `get_` before functions and methods that return data? This way you can have 

`get_output()`  and `output()`

Personally I use `render()` when printing data.

**Comment by trsenna** [comment]
Hi, just let me throw some ideas - but before that I like the idea of xxx/get_xxx (print/get) or xxx/the_xxx (get/print). Also I'd like to say I do not see problems with the render name. Yii framework for example goes with the render method name. See https://github.com/yiisoft/yii-app/blob/master/src/controllers/SiteController.php#L63 - also Plates follows the render method name.

$view->partial()
$view->part()
$view->view()
$view->content()
$view->template()

About the fetch method I would prefer to just remove it and keep only the "render", but change the render to return the string content. If I need to print it I just would call the native php function, echo or php echo tag.

**Comment by trsenna** [comment]
Throwing some more options, but keeping render to return the html content

$view->render() // get
$view->show() // print

$view->render() // get
$view->display() // print

**Comment by justintadlock** [comment]
I should probably clear some things up that I didn't cover in the original post above.

This is not just in reference to the `View` class.  We consistently use this terminology across Hybrid Core, Hybrid Breadcrumbs, Hybrid Carbon, Hybrid Font, and the theme for returning and outputting HTML.

`Hybrid\Post\render_title()`, for example.

Most of this stems from `Hybrid\Contracts\Fetchable` and `Hybrid\Contracts\Renderable`.

So, `partial()`, `part()`, `template()`, and other view/template-specific terms wouldn't work outside of views.  We could discuss changing those specifically for views, but that's another ticket and out of scope for this ticket.  Right now, I want to address the general terminology.

-------

I always say nothing is completely set in stone, but I'm pretty set on a few of things:

- The functions/methods must use a verb (e.g., `render_title()`, `print_date()`).
- `get_*()` is probably a non-starter just because I want it separate and to have a clear interface for just HTML strings.
- Both a function for outputting/printing and for returning/getting the HTML are going in.

------

Options I'm seeing right now:

**For output:**

- `print()`
- `show()`
- `display()`

**For returning:**

- `render()`
- `fetch()`
- `yield()`
- `toHtml()`

**Comment by justintadlock** [comment]
Just noting that `print` is a reserved keyword in PHP and can't be a function name, even within a namespace, so that's out.

**Comment by justintadlock** [comment]
I think it's important to not look at this in isolation.  Code has to _feel_ right too.  Here's an example from `resources/views/comment/default.php` where we're both printing and returning.

I'm using the `display` terminology for printing and `render` for returning.

```php
<li <?php Hybrid\Attr\display( 'comment' ) ?>>

	<header class="comment__meta">
		<?php echo get_avatar( $data->comment, $data->args['avatar_size'], '', '', [ 'class' => 'comment__avatar' ] ) ?>

		<?php Hybrid\Comment\display_author( [ 'after' => '<br />' ] ) ?>
		<?php Hybrid\Comment\display_permalink( [
			'text' => sprintf(
				// Translators: 1 is the comment date and 2 is the time.
				esc_html__( '%1$s at %2$s' ),
				Hybrid\Comment\render_date(),
				Hybrid\Comment\render_time()
			)
		] ) ?>
		<?php Hybrid\Comment\display_edit_link( [ 'before' => Mythic\sep() ] ) ?>
		<?php Hybrid\Comment\display_reply_link( [ 'before' => Mythic\sep() ] ) ?>
	</header>
```

**Comment by brettsmason** [comment]
From someone without an in depth PHP background, what we already had made sense to me.
It's more than likely because I'm used to how they are at the moment though, so take it with a pinch of salt.

**Comment by erikjoling** [comment]
```
<?php Hybrid\Comment\display_edit_link( [ 'before' => Mythic\sep() ] ) ?>
<?php Hybrid\Comment\display_reply_link( [ 'before' => Mythic\sep() ] ) ?>
```
You'd probably want to use `Mythic\render_sep()` as well ^^

**Comment by justintadlock** [comment]
After some internal discussion, our current thoughts are:

- `display` to display/print/output HTML strings.
- `fetch` to return HTML strings.

We felt like `render` is going to be a confusing word any direction we go with it. At the moment, it doesn't feel right to use it at all.

I'm leaving this ticket open for further feedback.

**Comment by wpmonty** [comment]
How would you feel about something more on the nose: `get_html()`

You could take the approach of `echo get_html(;)` or pass an argument to do so with `get_html(..., $print = true)

These are not uncommon in WP core as well.

**Comment by justintadlock** [comment]
`Hybrid\Post\get_html_title()` doesn't feel natural to me.  `Hybrid\Post\get_title_html()` feels a bit better.  In both cases, we're adding an extra word, which I'm not a huge fan of.

I'd also like to keep this one word to avoid things like the following (this is the coding style we use):

```
// Class methods follow camel-casing:
SomeClass {

	public function getHtml();
}

// Function methods follow snake-casing:
function get_xxxx_html();
```

**Comment by justintadlock** [comment]
I do want to note that we're going to revisit using `render()` for returning.  

Our main group has been running with `fetch()` + `render()` for months.  So, we need some time for our minds to adjust to get away from `render()` in order to reintroduce it.

**Comment by justintadlock** [comment]
I'm going to close this one as fixed.  We've been using `display` (for output) and `render` (for return) without issue for a few days.
