### ISSUE TITLE
Establishing a standard for Gutenberg styles 

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#37]
It's not in the theme yet, but we need to have Gutenberg block styles ready to go out of the box.

## Folder

A `resources/styles/blocks` folder is going to be in the theme.  That's a definite.  Everything else below is what we need to figure out.

## Files

We could populate the `blocks` folder with a simple `_index.scss` for theme authors to get started with a completely blank slate.  Or, we could add the files right off the bat.

Here's a look at most (not sure if I've got all yet) blocks and a proposed file naming system for core blocks:

```
/blocks
	/_wp-block-button.scss
	/_wp-block-categories.scss
	/_wp-block-code.scss
	/_wp-block-columns.scss
	/_wp-block-cover-image.scss
	/_wp-block-embed.scss
	/_wp-block-file.scss
	/_wp-block-gallery.scss
	/_wp-block-image.scss
	/_wp-block-latest-posts.scss
	/_wp-block-preformatted.scss
	/_wp-block-pullquote.scss
	/_wp-block-quote.scss
	/_wp-block-separator.scss
	/_wp-block-subhead.scss
	/_wp-block-table.scss
	/_wp-block-verse.scss
```

## Default styles

Do we include default styles for Gutenberg?  These could just be copy-pasted, essentially, from core as a base.

Mythic is 100% designed with the idea that theme authors will be building Gutenberg-ready themes.  The question is how far we want to go.  We have to balance between getting in the theme author's way and getting them off on the right foot.

In `app/functions-assets.php`, I have the code for disabling Gutenberg's default styles.  This is commented out right now.  Whether we uncomment will be largely dependent on whether we package any default styles.

```php
add_action( 'enqueue_block_editor_assets', function() {

	wp_enqueue_style( 'mythic-editor', asset( 'styles/editor.css' ), null, null );

	// Unregister core block and theme styles.
	// wp_deregister_style( 'wp-core-blocks' );
	// wp_deregister_style( 'wp-core-blocks-theme' );

	// Re-register core block and theme styles when empty string. This is
	// necessary to get styles set up correctly.
	// wp_register_style( 'wp-core-blocks', '' );
	// wp_register_style( 'wp-core-blocks-theme', '' );

}, 5 );
```

**Comment by brettsmason** [comment]
This is an area I've been struggling to reach a conclusion on too.

I have a very similar setup to what you describe here: https://github.com/brettsmason/luxe/tree/master/resources/styles/blocks

However every publically available theme I've seen for Gutenberg (including those by Automattic) has added their own styles on top of the core styles, which has started to make me doubt my decision slightly.

Ultimately though I think its the correct direction, even though it is a lot more work (at least to get a baseline anyway).

One thing to note - you probably need a partial for custom colour classes and font size classes too.

**Comment by justintadlock** [comment]
What we need at this point in the process is to make sure all the styles are working on both the front and back end.  Outside of that, I like where we're at.
