### ISSUE TITLE
Getting ready for Gutenberg

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/mythic#4]
In my opinion starter theme should support up coming editor, code name Gutenberg. For me support means:

- Theme support for `align-wide`.
- Theme support for `editor-color-palette`.
- Dequeue Core block styles from front-end.
- Adding styles for blocks that needs it. For example `<hr>`, `<tables>`, and `<blockquote>` already have styles.
- Enqueue block related styles back to editor.
- Trying to have system that allows easily adding styles for custom blocks (from public or private plugins).

For organising SASS/CSS I'm thinking that there should be `blocks.css` imported automatically from SASS files. Then this file can be enqueued in the editor.

`blocks.css` could have:

- All html elements like `<table>`, `<hr>` etc.
- Typography.
- All `wp-block-*` related styles like for `wp-block-button`.

These styles might need to be wrapped inside `.edit-post-visual-editor`class but this can change.

**Comment by justintadlock** [comment]
I think the only thing missing with this right now might be the `.alignwide` and `.alignfull` classes.  I'd be in favor of adding some defaults for all of core's `.align*` classes.  A good set of defaults would be good.
