### ISSUE TITLE
Missing import of _a11y.scss

### ISSUE THREAD

**Issue by tiborp** [justintadlock/mythic#42]
I noticed that the /utilities/__a11y.scss file is not (yet?) imported in screen.scss.

Would it also be an idea to add some basic styles to it for .screen-reader-text? 
https://rianrietveld.com/2015/04/04/the-screen-reader-text-class-why-and-how/

**Comment by justintadlock** [comment]
> Would it also be an idea to add some basic styles to it for .screen-reader-text?

Yes, some defaults for `.screen-reader-text` and/or `.skip-link` would be most welcome here.
