### ISSUE TITLE
Use an _index.scss for /styles/* subfolders

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#43]
One thing I've been considering is adding an `_index.scss` file to each of the subfolders under `/resources/styles`.

For example, a `/components/_index.scss` would import all of the other `.scss` files from `/components`.  Then, in `/resources/styles/screen.scss` (or elsewhere), we could simply import them all with one line of code:

```scss
@import 'components/index';
```

Anyone see any potential downsides to this?  Or, alternative solutions?

**Edit:** This could potentially be an `__index.scss` (double underscore) file too to put it at the top of the file list.

**Comment by RhinoRichan** [comment]
I think that approach is nice, I assume will be like this
```
.app-header {
@import "branding";
@import "menu";
}
```
because SCSS support BEM can write  &__branding, &__menu

**Comment by erikjoling** [comment]
> Edit: This could potentially be an __index.scss (double underscore) file too to put it at the top of the file list.

Nice! I hate it when my _index.scss file just drifts among the others

**Comment by justintadlock** [comment]
Closing as fixed.
