### ISSUE TITLE
Should we dump autoload after theme rename?

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#48]
When running the `rename` command, the `Mythic` namespace is replaced with the theme's new namespace in `composer.json`.  This means that `composer dump-autoload` needs to be called to regenerate the autoload files.

I've added this extra step to the installation docs.

One proposed solution was to change the `rename` script in `package.json` to this:

```json
"scripts": {
	"rename": "theme-claim && composer dump-autoload"
}
```

My worry with this is that on some setups the `composer` command is `composer.phar`.

Perhaps we should just leave it be and keep this in the installation docs.  Opening this ticket for discussion.

**Comment by Horttcore** [comment]
Might `$(which composer) update` solve this issue?

**Comment by justintadlock** [comment]
This is currently a part of the theme rename section of the installation doc: https://github.com/justintadlock/mythic/wiki/Installation#renaming-the-theme

I think this is the best course of action too and am closing this ticket.
