### ISSUE TITLE
Check for file before trying to export

### ISSUE THREAD

**Issue by m-e-h** [justintadlock/mythic#52]
Some of these files may not exist on the `export`  https://github.com/justintadlock/mythic/blob/master/webpack.mix.export.js#L23-L31. 
I'm getting 
```Error: ENOENT: no such file or directory, stat '/home/marty/vagrant-local/www/wordpress-default/public_html/wp-content/themes/forsite/readme.md'``` 
cause I'm using the generated `README.md` from github.

**Comment by justintadlock** [comment]
That was always on my list -- reminder to self to create tickets so I don't forget things.

I believe there was a Node function that could handle this.
