### ISSUE TITLE
Adding setup script

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/mythic#6]
This is not priority but would be nice to have a setup script. It would ask your

- theme name.
- theme slug.
- dev URL.

After setup have run, you have a ready to go theme without manually doing any search and replace. [One example of setup.sh file](https://github.com/samikeijonen/foxer/blob/master/setup.sh).

[Sage also have setup process](https://github.com/roots/sage#theme-installation) when building from composer. That's another example.

**Comment by brettsmason** [comment]
Also a nice one in the Tonik theme. Details here: https://labs.tonik.pl/theme/docs/configuration/

**Comment by justintadlock** [comment]
@samikeijonen - Do you have a tutorial where you learned how to set up that file?  It's something I definitely want to do.

**Comment by samikeijonen** [comment]
My example file is almost  a copy of [Aucor starter theme file setup.sh](https://github.com/aucor/aucor-starter/blob/master/setup.sh). I just followed that but haven't  read any tutorials of it.

**Comment by samikeijonen** [comment]
I also like a lot how Tonik and Sage setup goes because you can fetch the starter theme via composer.

**Comment by justintadlock** [comment]
I added the `theme-claim` package this morning by @m-e-h in https://github.com/justintadlock/mythic/commit/e83af586b103c0e7aa2c4a29e2520c603b5eef56.

Minus a couple of small things, it's ready.  I'm leaving this ticket open until we're satisfied with that.

For testing, run:

```bash
npm run rename
```

**Comment by justintadlock** [comment]
I'm pretty satisfied with `theme-claim` at this point, so I'm closing this out.  If anyone wants to explore alternatives down the road, we can open new tickets.
