### ISSUE TITLE
Adding phpcs.xml file

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/mythic#7]
Project code should be checked using [PHPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards). In most cases there should be [custom `phpcs.xml`](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#using-a-custom-ruleset) for creating custom ruleset good for project.

Couple of examples:

- [`phpcs.xml` file in _s](https://github.com/Automattic/_s/blob/master/phpcs.xml.dist).
- [A little modified version of that](https://github.com/samikeijonen/foxer/blob/master/phpcs.xml).

This way we can also check PHP compatibility for different versions.

**Comment by justintadlock** [comment]
This is probably one of the biggest projects left for the theme before the 1.0.0 release.  We need to pay attention to the WPTRT coding standards project.  We'll want to take advantage of that and integrate it with any custom rules.

**Comment by GaryJones** [comment]
Please name it `.phpcs.xml.dist`, and add `phpcs.xml` and `.phpcs.xml` to the `.gitignore` file.

This allows the distributed config file to be trumped by a local config file.

@samikeijonen I'll add some feedback about your config file, to your repo :-)

**Comment by justintadlock** [comment]
Closing this specific ticket as fixed. We should open new tickets to address other issues.

In particular, our end goal would be to utilize the WP TRT standards.
