### ISSUE TITLE
How to use Mythic as a child theme itself

### ISSUE THREAD

**Issue by ThatGuySam** [justintadlock/mythic#77]
Awesome theme! I really love Laravel Mix and I love having linting so I don't have to worry if I'm doing theme development the right way. 

I was wondering if there is a simple way to use Mythic as child theme itself so can I start with a theme that already has a lot of features I want(ex: Woocommerce Integration) and then rebuild/add certain features with Mythic. 

The theme I'm wanting to "extend" so to speak is Salient: https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266

I've tried this before with Sage to terrible results so it may be a wild goose chase but any advice is appreciated.

**Comment by justintadlock** [comment]
Mythic was created so others could create parent themes.  Plus, it loads up the Hybrid Core framework (and potentially other PHP packages in the future).

You could gut out everything in the theme but Laravel Mix and the other build-related stuff and use it as a child theme, but it'd be just as easy to build from scratch.

**Comment by ThatGuySam** [comment]
Okay, I might take to reverse approach by starting with a barebones child theme and pull in parts of Mythic one at a time starting with Laravel Mix to avoid collisions with the parent theme.
